Models/Event.cs
using System.ComponentModel.DataAnnotations;

namespace EMS_App.Models
{
    public class Event
    {
    
        [Required]
        [Key]
        public string Ename { get; set; }
        [Required]
        public string Ediscription { get; set; }
        [Required]
        public string EBanner { get; set; }
    }
}

Controllers/EventsController.cs
using EMS_App.Data;
using EMS_App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace EMS_App.Controllers
{
    public class EventsController : Controller
    {
        private readonly EMSContext _db;

        public EventsController(EMSContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Event> events = _db.Event.ToList();
                        return View();


        }
    }
}

Views/Events/Add.cshtml
@model EMS_App.Models.Event
<div class="mb-3"><h1>Add Event</h1></div>

<form method="post" action="Add">
    <div class="mb-3">
        <label for="" class="form-label">Event Heading</label>
        <input type="text" class="form-control" asp-for="eventHeader" placeholder="Enter event heading here"/>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Event Short Description</label>
        <input type="text" class="form-control" asp-for="eventShortDescription" placeholder="Enter event short description (two lines) here" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Event Description</label>
        <textarea class="form-control" id="tiny" asp-for="eventDescription" placeholder="Enter event description here"></textarea>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Event Start Time</label>
        <input type="datetime-local" class="form-control" asp-for="eventStartTime"/>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Event End Time</label>
        <input type="datetime-local" class="form-control" asp-for="eventEndTime" />
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
    <a class="btn btn-default" asp-area="" asp-controller="Events" asp-action="Index">Cancel</a>
</form>

Views/Events/Index.cshtml
@model List<EMS_App.Models.Event>

<link href="~/css/event.css" rel="stylesheet" asp-append-version="true" />
<h3 class="page-title text-center">Timeline</h3>
<ul class="timeline">
    <li class="timeline-line"></li>
    <li class="timeline-group">
        <a href="#" class="btn btn-primary"><i class="fa fa-calendar"></i>December 6th, 2023</a>
    </li>
</ul>
<ul class="timeline">
    <li class="timeline-line"></li>
    @foreach (Event e in Model)
    {
        <li class="timeline-item">
            <div class="timeline-badge"><a href="#"></a></div>
            <div class="timeline-panel">
                <div class="timeline-heading">
                    @e.eventHeader
                    <div class="timeline-date"><i class="fa fa-clock-o"></i> @e.eventStartTime.ToString("MMMM dd, yyyy - HH:mm")</div>
                </div>
                <div class="timeline-content">
                    <p>@Html.Raw(e.eventShortDescription)</p>
                </div>
                <div class="timeline-footer">
                    <small class="text-muted">Duration = @(e.eventEndTime - e.eventStartTime)</small>
                </div>
            </div>
        </li>
    }
    <!--
        <li class="timeline-item">
            <div class="timeline-badge"><a href="#"></a></div>
            <div class="timeline-panel">
                <div class="timeline-heading">
                    Minor Update
                    <div class="timeline-date"><i class="fa fa-clock-o"></i> November 7, 2015</div>
                </div>
                <div class="timeline-content">
                    <ul>
                        <li><code>CSS</code> added line 205 to 207 for <i>timeline date</i></li>
                        <li><code>CSS</code> changed line  269 from <i>1199px to 991px</i></li>
                        <li><code>HTML</code> + <code>CSS</code> and many more ... </li>
                    </ul>
                </div>
                <div class="timeline-footer">
                    <small class="text-muted">Timeline Footer</small>
                </div>
            </div>
        </li>
        <li class="timeline-item">
            <div class="timeline-badge"><a href="#"></a></div>
            <div class="timeline-panel">
                <div class="timeline-heading">Welcome to GongKia Timeline</div>
                <div class="timeline-content">
                    <p>Eu pid nunc urna integer, sed, cras tortor scelerisque penatibus facilisis a pulvinar, rhoncus sagittis ut nunc elit! Sociis in et? Rhoncus, vel dignissim in scelerisque. Dolor lacus pulvinar adipiscing adipiscing montes! Elementum risus adipiscing non, cras scelerisque risus penatibus? Massa vut, habitasse, tincidunt!</p>
                    <p>Eu pid nunc urna integer, sed, cras tortor scelerisque penatibus facilisis a pulvinar, rhoncus sagittis ut nunc elit! Sociis in et?</p>
                </div>
            </div>
        </li>
        <li class="timeline-item">
            <div class="timeline-badge"><a href="#"></a></div>
            <div class="timeline-panel">
                <div id="about" class="timeline-heading">About Timeline</div>
                <div class="timeline-content">
                    <p><img class="img-responsive" src="http://placeimg.com/640/240/people"></p>
                    <p>Rubber cheese say cheese bocconcini. Caerphilly cheese and biscuits squirty cheese airedale lancashire cheese and biscuits rubber cheese squirty cheese. Ricotta fromage frais port-salut danish fontina cream cheese queso edam ricotta. Gouda monterey jack blue castello stilton rubber cheese.</p>
                </div>
            </div>
        </li>
        <li class="timeline-item">
            <div class="timeline-badge"><a href="#"></a></div>
            <div class="timeline-panel">
                <div id="services" class="timeline-heading">Services Timeline</div>
                <div class="timeline-content">
                    <p>Eu pid nunc urna integer, sed, cras tortor scelerisque penatibus facilisis a pulvinar, rhoncus sagittis ut nunc elit! Sociis in et? Rhoncus, vel dignissim in scelerisque. Dolor lacus pulvinar adipiscing adipiscing montes! Elementum risus adipiscing non, cras scelerisque risus penatibus? Massa vut, habitasse, tincidunt!</p>
                    <div class="row services-list">
                        <div class="col-xs-4"><img class="thumbnail img-responsive" src="http://placeimg.com/640/640/tech"></div>
                        <div class="col-xs-4"><img class="thumbnail img-responsive" src="http://placeimg.com/640/640/tech"></div>
                        <div class="col-xs-4"><img class="thumbnail img-responsive" src="http://placeimg.com/640/640/tech"></div>
                    </div>
                    <p>Cottage cheese rubber cheese everyone loves. Cow monterey jack cheesy grin cauliflower cheese cheesy feet mozzarella emmental blue castello. Lancashire boursin blue castello taleggio babybel bocconcini fondue cheese triangles. Fromage frais cheese strings airedale boursin st. agur blue cheese squirty cheese pecorino.</p>
                </div>
            </div>
        </li>
        <li class="timeline-item">
            <div class="timeline-badge"><a href="#"></a></div>
            <div class="timeline-panel">
                <div class="timeline-heading">Media Timeline</div>
                <div class="timeline-content">
                    <p>Eu pid nunc urna integer, sed, cras tortor scelerisque penatibus facilisis a pulvinar, rhoncus sagittis ut nunc elit! Sociis in et? Rhoncus, vel dignissim in scelerisque. Dolor lacus pulvinar adipiscing adipiscing montes! Elementum risus adipiscing non, cras scelerisque risus penatibus? Massa vut, habitasse, tincidunt!</p>
                    <div class="timeline-embed">
                        <iframe width="478" height="320" src="https://www.youtube.com/embed/G7q07dyIsX8?list=RDEMeI4zMDi6uvY6C8nWWWoZ1A&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </li>
        <li class="timeline-item">
            <div class="timeline-badge"><a href="#"></a></div>
            <div class="timeline-panel">
                <div class="timeline-heading">Contact Us Timeline</div>
                <div class="timeline-content">
                    <p>Eu pid nunc urna integer, sed, cras tortor scelerisque penatibus facilisis a pulvinar, rhoncus sagittis ut nunc elit! Sociis in et? Rhoncus, vel dignissim in scelerisque. Dolor lacus pulvinar adipiscing adipiscing montes! Elementum risus adipiscing non, cras scelerisque risus penatibus? Massa vut, habitasse, tincidunt!</p>
                    <div class="timeline-embed">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d15936.386801163795!2d101.61008935000001!3d3.0688275999999997!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2smy!4v1446881552869" width="478" height="320" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </li>
    </ul>
    <ul class="timeline">
        <li class="timeline-line"></li>
        <li class="timeline-group">
            <a href="#" class="btn btn-primary"><i class="fa fa-calendar"></i> 2014</a>
        </li>
    </ul>
        -->
    <ul class="timeline">
        <li class="timeline-line"></li><!-- /.timeline-line -->
        <li class="timeline-item block">
            <div class="timeline-badge"><a rel="tooltip" title="" data-context="inverse" data-container="body" class="border-silc" href="#" data-original-title="block highlight"></a></div>
            <div class="timeline-panel">
                <div class="timeline-content">
                    <div class="text-center">
                        <p>
                            <a href="#" class="kit-avatar kit-avatar-64">
                                <i class="fa fa-android" style="font-size:64px;"></i>
                            </a>
                        </p>
                        <h4>Event Location - SMU</h4>
                        <p class="timeline-date">From 9 AM on December 6th, 2023 onwards till 6 PM on December 7th, 2023</p>
                        <p>The SMU Tech Summit will welcome technology leaders, industry disruptors and tech workers from across our 4 Atlantic provinces and beyond.</p>
                        <p>Theme for this year is <b>“The Future is now”</b>.</p>
                        <div class="timeline-embed">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2839.3220753009755!2d-63.584031924069805!3d44.63133388862253!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4b5a223f94860a5d%3A0xdd0961dfd426d80d!2sSaint%20Mary&#39;s%20University!5e0!3m2!1sen!2sca!4v1702009804583!5m2!1sen!2sca" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    </ul>
</ul>