Controllers/ProgramController.cs
using EMS_App.Data;
using EMS_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EMS_App.Controllers
{
    public class ProgramController : Controller
    {
        private readonly EMSContext eMSContext;

        public ProgramController(EMSContext eMSContext)
        {
            this.eMSContext = eMSContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var events = await eMSContext.events.ToListAsync();
            var newEve = events.OrderBy(m => m.eventStartTime).ToList();
            return View(newEve);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Models.Program e)
        {
            var ent = new Models.Program()
            {
                eventDescription = e.eventDescription,
                eventID = new Guid(),
                eventHeader = e.eventHeader,
                eventStartTime = e.eventStartTime,
                eventEndTime = e.eventEndTime,
                eventShortDescription = e.eventShortDescription
            };

            await eMSContext.events.AddAsync(ent);
            await eMSContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EMS_App.Data;
using EMS_App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.VisualBasic;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Identity;

namespace EMS_App.Controllers
{
    public class TicketsController : Controller
    {
        private readonly EMSContext _context;

        public TicketsController(EMSContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            return _context.Ticket != null ?
                        View(await _context.Ticket.ToListAsync()) :
                        Problem("Entity set 'EMSContext.Ticket'  is null.");
        }

        // GET: /Tickets/Checkout/ 
        [HttpPost]
        public ActionResult ProceedtoCheckout(ICollection<Ticket> model)
        {
            CheckoutView checkoutView = new CheckoutView();
            checkoutView.Ticket = model.ToList();
            checkoutView.Purchase = new Purchase();
            checkoutView.Purchase.Uemail = User.Identity.Name;
            return View("Checkout", checkoutView);
        }

        [HttpPost]
        public IActionResult Checkout(CheckoutView model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var dbContextTransaction = _context.Database.BeginTransaction())
                    {
                        _context.Billing.Add(model.Billing);
                        _context.Payment.Add(model.Payment);
                        _context.SaveChanges();
                        model.Purchase.BillingId = model.Billing.BillingId;
                        model.Purchase.PaymentId = model.Payment.PaymentId;
                        model.Purchase.Created = DateTime.Now;
                        _context.Purchase.Add(model.Purchase);
                        _context.SaveChanges();
                        TicketPurchase ticketpurchase = new TicketPurchase();
                        for (int i = 0; i < model.Ticket.Count; i++)
                        {
                            if (model.Ticket[i].Quantity > 0)
                            {
                                ticketpurchase.OrderId = model.Purchase.OrderId;
                                ticketpurchase.TicketId = model.Ticket[i].TicketId;
                                ticketpurchase.Quantity = model.Ticket[i].Quantity;
                                _context.TicketPurchase.Add(ticketpurchase);
                                var ava = _context.Ticket.Find(ticketpurchase.TicketId);
                                if (ava != null)
                                {
                                    ava.Availability = ava.Availability - ticketpurchase.Quantity;
                                    _context.Update(ava);
                                }
                                _context.SaveChanges();
                            }
                        }
                        dbContextTransaction.Commit();
                    }
                }
                catch (Exception ex)
                {
                    return View("Status", model);
                }
                //return RedirectToAction("Status", new { OrderId = model.Purchase.OrderId});
                return View("Status", model);
            }
            return View(model);
        }
        public IActionResult Status(CheckoutView checkout)
        {
            return View(checkout);
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult ValidateCard([Bind(Prefix = "Payment.CardNumber")] long CardNumber, [Bind(Prefix = "Payment.CardName")] String CardName, [Bind(Prefix = "Payment.CardType")] String CardType)
        {
            String numberString = CardNumber.ToString();

            if (numberString.Length < 15 || numberString.Length > 16)
            {
                return Json($"Invalid Card Length");
            }
            if (CardType.Equals("Visa"))
            {
                if (!(numberString.StartsWith("4") && numberString.Length == 16))
                {
                    return Json($"Invalid Visa Card Number");
                }
            }
            if (CardType.Equals("Master Card"))
            {
                int CardNumberPrefix = int.Parse(numberString.Substring(0, 2));
                if (!((CardNumberPrefix >= 51 && CardNumberPrefix <= 55) && numberString.Length == 16))
                {
                    return Json($"Invalid Master Card Number");
                }
            }
            if (CardType.Equals("American Express"))
            {
                if (numberString.Length != 15)
                {
                    return Json($"Invalid American Express Number");
                }
                if (!(numberString.StartsWith("34") || numberString.StartsWith("37")))
                {
                    return Json($"Invalid American Express Number");
                }
            }
            return Json(true);
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult ValidatePostalCode([Bind(Prefix = "Billing.BPostalCode")] String PostalCode, [Bind(Prefix = "Billing.BCountry")] String Country)
        {
            if (Country.Equals("United State"))
            {
                if (!Regex.Match(PostalCode, "^[0-9]{5}(?:-[0-9]{4})?$").Success)
                    return Json($"Invalid US Postal Code");
            }
            else if (Country.Equals("Canada"))
            {
                if (!Regex.Match(PostalCode.ToUpper(), "^[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ] [0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]$").Success)
                    return Json($"Invalid CA Postal Code");
            }
            return Json(true);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMU Tech Summit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS_App.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.min.js"></script>

</head>
<body>
    <header>
        <script src="https://cdn.tiny.cloud/1/u0128pf9wcotm0zpvoque76f8oujnf866dxqe3qrwnsmydwp/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
        <script>
            tinymce.init({
                selector: 'textarea#tiny',
                plugins: [
                    'a11ychecker', 'advlist', 'advcode', 'advtable', 'autolink', 'checklist', 'export',
                    'lists', 'link', 'image', 'charmap', 'preview', 'anchor', 'searchreplace', 'visualblocks',
                    'powerpaste', 'fullscreen', 'formatpainter', 'insertdatetime', 'media', 'table', 'help', 'wordcount'
                ],
                toolbar: 'undo redo | a11ycheck casechange blocks | bold italic backcolor | alignleft aligncenter alignright alignjustify |' +
                    'bullist numlist checklist outdent indent | removeformat | code table help'
            })
        </script>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SMU Tech Summit</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Program" asp-action="Index">Programs</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                                Admin
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Program" asp-action="Add">Add Program</a></li>
                                <li><a class="dropdown-item" href="#">Add Ticket</a></li>
                                <li><a class="dropdown-item" href="#">Add Speaker</a></li>
                            </ul>
                        </li>
                        -->
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container text-center">
            &copy; 2023 - SMU Tech Summit - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["SignUp"] != null)
{

    <script type="text/javascript">


        Swal.fire({
            icon: 'success',
            title: 'Operation Successful',
            text: '@TempData["You Have successfully Sign Up With Us"]',
        });

    </script>
}

@if (TempData["delete"] != null)
{

    <script type="text/javascript">
        Swal.fire({
            icon: 'success',
            title: 'Operation Successful',
            text: '@TempData["delete"]',
        });
    </script>
}

@if (TempData["edit"] != null)
{

    <script type="text/javascript">
        Swal.fire({
            icon: 'success',
            title: 'Operation Successful',
            text: '@TempData["edit"]',
        });
    </script>
}




<!-- Include SweetAlert2 JS -->